### ISSUE TITLE
What should our policy be for squashing commit history in Pull Requests?

### ISSUE THREAD

**Issue by amcgee** [WellDone/MoMo-Firmware#120]
I think I'm in favor of squashing to make the log more descriptive and easy to read.

See http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit/

**Comment by timburke** [comment]
I support this.  On my latest PR I squashed the commits into one. Do we 
want to make it a policy of squashing commits for each PR?  It was easy 
to do based on the link you sent out and I agree that it makes things 
much more readable and descriptive.  It should also help with reverting 
a PR easier.
- tim

**Comment by amcgee** [comment]
Awesome, agreed.  Let's make that our policy.

On Tue, Oct 7, 2014 at 10:24 PM, timburke notifications@github.com wrote:

> I support this. On my latest PR I squashed the commits into one. Do we
> want to make it a policy of squashing commits for each PR? It was easy
> to do based on the link you sent out and I agree that it makes things
> much more readable and descriptive. It should also help with reverting
> a PR easier.
> - tim
> 
> On 10/06/2014 11:09 AM, Austin McGee wrote:
> 
> > I think I'm in favor of squashing to make the log more descriptive and
> > easy to read.
> > 
> > See
> > 
> > http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit/
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/WellDone/MoMo-Firmware/issues/120.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WellDone/MoMo-Firmware/issues/120#issuecomment-58311766
> .

## 

Austin McGee
austinwm@gmail.com
(510) 200-8486

**Comment by timburke** [comment]
Word.
