### ISSUE TITLE
Revise Controller Board

### ISSUE THREAD

**Issue by timburke** [WellDone/MoMo-Firmware#137]
Prepare another revision of the controllerboard hardware.  Planned features are:
- [X] Add micro-usb plug for power (R/A plug)
- [X] Remove backup battery
- [x] Add backup capacitor with 1 minute of charge time to not lose rtcc time when changing the battery
- [x] Add ability for the board to disconnect power from the battery for say 100 ms so that it can reset itself without needing to unplug the battery.  
- [x] Remove DC-DC Converter
- [x] Integrate Tim Cronin's current sensor
- [x] Integrate BTLE
- [x] Move programming Data line from ALARM to data to make reflashing with a bootloader easier. 
- [x] Connect controller lines:
  - Batt sample
  - Vext sample
  - control peripheral power
  - control reset power
- [x] Add RF filtering caps to 2.8V regulator
  - Add 10 pf and 33 pf 0402 in parallel to get right resonance properties
- [x] Replace P-MOSFET with cheaper version:
  IRLML6401PBFCT-ND -> IRLML6402PBFCT-ND
  (use one for charge controlling and one for turning off module power.

**Comment by amcgee** [comment]
This all sounds good, I really like the software hard-reset capability.  I
assume that 100 ms delay is implemented in hardware?

Should we consider a different connector for the battery?  Without having
to pull it for hard resets things get better, but at scale it might be
tough to distribute crimping tools.

**Comment by timburke** [comment]
@amcgee A point for discussion:

I can easily change the power connector to a microusb.  This will fit on the board pretty well and actually take up less space since we're getting rid of the DC-DC converter.  However, considering the width of the microusb plug connector, it won't be possible to plug a microusb into the board when it's in the waterproof case.  By gutting a lot of the board space to inset the microusb connector a lot I could make it possible to have the microusb be plugged in while the board is in the case.  However, I don't think this is the best option.  When we assemble these units for the field, we should just solder wires from the solar panel to the boards.  Having the solar panels terminate in a right-angle microusb cable seems to me to just add wasteful expense since we'll have to buy panels that have the right microusb connector or be in the position of soldering or crimping a microusb cable to the panel in order to then plug it in to board.  I see the purpose of the microusb to be for easier powering of the unit when it's not in a box connected to a solar panel.  So I propose the following:
- Micro-usb connector that will not be accessible when the unit is in its box and two solder terminals for connecting wires from a solar panel.  We could also have a separate connector for the solar panel but I honestly think it's easier to just solder it than to crimp the connectors.  

Thoughts?

**Comment by timburke** [comment]
Voltage supervisor and reset circuit.  It looks straightfoward to add hw reset functionality and there are already chips that do what we want, which is really useful.  I propose 2 features, one for robustness and one for battery protection.  [This IC](http://www.digikey.com/product-detail/en/BD45312G-TR/BD45312GCT-ND/2749769) handles the core functionality and will disconnect the board from the li-ion battery when the battery voltage is below 3.1V.  It also has a manual reset that can be triggered by the pic24 or the bluetooth module to hw reset everything for 200 ms.  The batter backup for the PIC24 RTCC will be connected in front of this chip so that it always has battery power and the PIC won't lose time when it hw resets.

Chip cost is 56 cents @ 25 units.

**Comment by amcgee** [comment]
I think this sounds good to me!  The argument against solder points would be that it makes installation into the container much more permanent, and things like changing the battery can become more difficult, but I think this is an OK trade-off.  There could also be an off-board connector somewhere along the cable if this really becomes an issue.

The battery voltage supervisor seems like a great feature!

(documenting offline discussion) On our call today, we discussed allowing non-controller modules to trigger the hard reset, but decided it would be better to implement watchdog-timer resets on the controller (preventing the controller from locking up) and working to avoid situations where a module can lock the bus.  Implementing asynchronous RPCs (Issue #92) would help with this.

**Comment by timburke** [comment]
Remaining TODO Items:
- [x] Find diodes for D1, D2
- [x] Find caps 33pf and 10pf
- [x] Check necessary pullup and pulldown resistors
- [x] Choose shunt resistor since we need to use a different amplifier (low amplification models are not stocked)
- [x] Add polygons (vext and batt)
