### ISSUE TITLE
Module registration

### ISSUE THREAD

**Issue by amcgee** [WellDone/MoMo-Firmware#17]

**Comment by timburke** [comment]
The mib12 executive on the pic12 now does autoregistration upon reset.  I changed the momo_module_description structure to make it compatible with the pic12 (ints -> uint8) and changed some of the entries.  The pic12 now autoregisters 1 second after each reset.  It's tested and works fine.  The only issue is that if the pic12 resets repeatedly, it will keep requesting new addresses until the pic24 is exhausted.  A fix would be for each device on the bus to have a unique serial number, allowing for the pic24 to know who's asking and see if has an entry already for that pic and just return that address if so.

**Comment by amcgee** [comment]
This has been implemented by Tim and myself, let's open a new issue for the unique address issue.
