### ISSUE TITLE
pic12 MIB Code sends extra i2c stop after master rpc

### ISSUE THREAD

**Issue by timburke** [WellDone/MoMo-Firmware#18]
When the PIC12 mib code calls i2c_finish_transmission() it sends a stop.  Then it has to transition back to slave mode.  This causes another stop to be sent as the master streaming serial port (MSSP) is reset into slave mode. 

This doesn't appear to cause any problems currently but is not ideal.  Should investigate:
- if this second stop can be avoided by changing the way slave mode is reentered
- if we can just not send the first explicit stop and rely on this behavior when master mode is exited

**Comment by amcgee** [comment]
I believe this has been fixed with some of the MIB refactoring, but I might be wrong.  Tim?

**Comment by timburke** [comment]
I have not seen this issue with the new code so I believe it to be fixed.  We can reopen if not.
