### ISSUE TITLE
Sensor pulse counting

### ISSUE THREAD

**Issue by amcgee** [WellDone/MoMo-Firmware#2]
Wake from sleep when an event begins, count pulses until it's done, then write the timestamp and pulse count (volume) to memory.

**Comment by amcgee** [comment]
The last step - writing timestamp and pulse count to memory - will actually be a separate task.  When a tick hasn't registered in some amount of time (say 5 seconds) an alarm interrupt should push a "store_event" task to the main task loop.  This task will dump the in-program-memory counter and timestamp values to (flash) memory

**Comment by amcgee** [comment]
David, want to mark this closed?

**Comment by dclarino** [comment]
I haven't tested it with the reporting code yet. If that's good enough for you, then yeah, mark it closed

**Comment by amcgee** [comment]
Completed before v0.9 milestone
