### ISSUE TITLE
Port Battery Manager to New Architecture

### ISSUE THREAD

**Issue by timburke** [WellDone/MoMo-Firmware#25]
The pic24 needs to actively manage the lithium ion battery if one is connected.  This includes
- [ ] checking for fully charged (>4.1V) and disabling the charger
- [ ] logging battery level periodically in debug mode
- [ ] checking for external power source and using it to charge the battery

**Comment by amcgee** [comment]
Tim, I think this can be closed?

**Comment by timburke** [comment]
Yup.
