### ISSUE TITLE
Integrate MIB definitions into pic12 build process

### ISSUE THREAD

**Issue by timburke** [WellDone/MoMo-Firmware#36]
- MIB endpoints and application module information can now be specified in a simple domain specific language.  
- mibtool has been updated to automatically generate command_map.asm files from these .mib files
- the pic12 build system has been updated to integrate these build files into the build process

TODO:
- [x]  check for bugs
- [x] validate output for gsm_module and pv_module
- [x] send pull request

**Comment by amcgee** [comment]
Closing, since this has been integrated
