### ISSUE TITLE
Power management routines

### ISSUE THREAD

**Issue by amcgee** [WellDone/MoMo-Firmware#5]

**Comment by timburke** [comment]
ADC code is working for controlling the adc module.  Example usage is given in command_handlers.c:handle_adc.  Next step to make the battery management state machine.  

I will probably implement this as a periodic task that checks if the battery voltage is below 4 volts and then enables the solar panel to charge it until it reaches say 4.15 volts.  Then the panel will be disabled until the battery falls below 4 volts again.  This hysteresis will prevent repetitively topping off the battery and breaking it.

**Comment by timburke** [comment]
Battery management code is integrated into dev.  Code charges the battery until 4.15V and allows it to discharge to 4V before resuming charging.
