### ISSUE TITLE
UART debug mode check

### ISSUE THREAD

**Issue by amcgee** [WellDone/MoMo-Firmware#8]
For some time (10s) after power-up, check for interrupts on UART2.  If one occurs, go into debug mode and poll for commands.

**Comment by timburke** [comment]
Integrated into dev.  UART2 is powered for between 10-20 seconds after an MCLR reset and disabled if no command (return key) is received in that window.  You must reset the pic to try again.  NB, this means that after programming you have to toggle MCLR to get a command prompt.
