### ISSUE TITLE
Support controller debug logging locally and via MIB RPC

### ISSUE THREAD

**Issue by amcgee** [WellDone/MoMo-Firmware#81]
I have most of this implemented, just working on a mechanism for reading the log entries (they are longer than the 20-byte MIB buffer limit)

**Comment by timburke** [comment]
One option is to just have the RPC take an offset into the log and give 
you the next 20 bytes.  The python wrapper calling the RPC can take care 
of reading the whole log and building it up bit by bit. This is what I 
did with the flash reading routines.

**Comment by amcgee** [comment]
Yeah, it just took some restructuring to do that when using flash_queue for the log storage.  Done now, testing.

**Comment by amcgee** [comment]
Implemented in #84
